class DiffDataPizza:
    START_URL = "https://www.pizzahut.com/index.php#/menu/pizza/popular-pizzas"
    MENU_BTN_ID = "lg-nav-menu"
    PIZZA_SECTION_BTN_ID = "lg-nav-pizza"
    CHEESE_PIZZA_ORDER_NOW_BTN_XPATH = "//a[@class ='btn btn-primary btnModal'][ancestor::div[@id='tile-cheese-pizza']]"
    CARRYOUT_BTN_ID = "find-occasion-carryout"
    # ZIP_CODE_FLD_CSS = ".ng-valid-maxlength.ng-touched"
    ZIP_CODE_FLD_CSS = ".col-md-12.col-xs-12.col-lg-12.right-inner-addon.ph-padding-left-0.ph-padding-right-0 > input"
    FIND_A_STORE_BTN_ID = "ph-find-store"
    LOCATIONS_BLOCKS_CSS = ".row.ph-font-12.custom-ct-di.ng-scope"
    # LOCATION_NUMBER_IN_BLOCK_CLS = "marker_label ng-binding"
    LOCATION_NUMBER_IN_BLOCK_CSS = ".ng-binding"
    PRE_ORDER_BTN_INSIDE_BLOCK_CLS = "btn ph-ordernow ng-scope btn-primary"
    PRE_ORDER_BTN_INSIDE_BLOCK_CSS = ".btn.ph-ordernow.ng-scope.btn-primary"
    CHEESE_PIZZA_SIZE_DROPDOWN_ID = "size-cheese-pizza"
    ADD_TO_ORDER_BTN_ID = "ato-cheese-pizza"
    CART_BTN_XPATH = "//a[@class='ph-ghost-link'][preceding-sibling::div[@id='cart-quantity-icon']]"
    SUBTOTAL_ORDER_SUM = "#sub-total + .col-sm-6.text-right >.ng-binding"

    NUMBER_ONE = "1"
    LARGE = "Large"

    ZIP_CODE = "78701"
